//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR2_ShershunovD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientZakaz
    {
        public int id { get; set; }
        public Nullable<int> idClienta { get; set; }
        public Nullable<int> idZakaza { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Zakaz Zakaz { get; set; }
    }
}
