//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR2_ShershunovD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudniki
    {
        public int id { get; set; }
        public string FIO { get; set; }
        public string Addres { get; set; }
        public string Phone { get; set; }
        public string Passport { get; set; }
        public int idOtdela { get; set; }
        public double Stavka { get; set; }
        public int Roleid { get; set; }
        public string Login { get; set; }
        public string Passwoed { get; set; }
    
        public virtual Otdel Otdel { get; set; }
        public virtual Role Role { get; set; }
        public virtual Zadachi Zadachi { get; set; }
    }
}
