//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR2_ShershunovD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zadachi
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Soderjanie { get; set; }
        public int idOtdela { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
