//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR2_ShershunovD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakaz()
        {
            this.ClientZakaz = new HashSet<ClientZakaz>();
            this.Otdel1 = new HashSet<Otdel>();
        }
    
        public int id { get; set; }
        public System.DateTime Date { get; set; }
        public string Soderjanie { get; set; }
        public string Trebovanie { get; set; }
        public string Platforma { get; set; }
        public string Otdel { get; set; }
        public System.DateTime Dedlain { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientZakaz> ClientZakaz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Otdel> Otdel1 { get; set; }
        public virtual User User { get; set; }
    }
}
